# Generated by Django 6.0.1 on 2026-01-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='load_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
