# Generated by Django 6.0.1 on 2026-01-16 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_alter_trip_load_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='closed_at',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='driver_salary',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='end_meter_reading',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='load_value',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='start_meter_reading',
        ),
        migrations.AddField(
            model_name='trip',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='drop_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trip',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='net_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='ticket_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='trips.trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_meter_image',
            field=models.ImageField(blank=True, null=True, upload_to='meter/'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_meter_image',
            field=models.ImageField(blank=True, null=True, upload_to='meter/'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=10),
        ),
    ]
