# Generated by Django 6.0.1 on 2026-01-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_remove_trip_closed_at_remove_trip_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='start_meter_reading',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
