# Generated by Django 6.0.1 on 2026-01-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_trip_start_meter_reading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='company',
        ),
        migrations.AlterField(
            model_name='trip',
            name='drop_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10),
        ),
    ]
