# Generated by Django 6.0.1 on 2026-01-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_remove_trip_company_alter_trip_drop_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
