# Generated by Django 6.0.1 on 2026-01-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_trip_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='end_meter_reading',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
