# Generated by Django 6.0.1 on 2026-01-29 12:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_trip_only_one_open_trip_per_driver'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trip',
            name='only_one_open_trip_per_driver',
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('driver',), name='open_trip'),
        ),
    ]
