# Generated by Django 6.0.1 on 2026-01-29 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_remove_trip_only_one_open_trip_per_driver_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trip',
            name='open_trip',
        ),
    ]
