# Generated by Django 6.0.1 on 2026-01-26 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0002_fuelentry_trip_alter_fuelentry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelentry',
            name='bill_image',
            field=models.ImageField(blank=True, null=True, upload_to='fuel_bills/'),
        ),
    ]
