# Generated by Django 6.0.1 on 2026-01-16 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_driverprofile_vehicle_alter_driverprofile_license_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverSalaryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rate_per_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.driverprofile')),
            ],
        ),
    ]
